name: Deploy CloudFormation
on:
  push:
    branches: ["master" ]
    paths:
      - 'function/lambda-one/stack-template.yaml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          
      - name: Deploy Stack
        run: |
          aws cloudformation deploy \
            --template-file function/lambda-one/stack-template.yaml \
            --stack-name lambda-stack \
            --capabilities CAPABILITY_IAM
        
